### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by jm134** [Kylart/MalScraper#1]
> const malScraper = require('mal-scraper')
/home/pi/node_modules/mal-scraper/src/info.js:152
      .then(async (items) => {
                  ^

SyntaxError: Unexpected token (

**Comment by Kylart** [comment]
What is your node version?

**Comment by jm134** [comment]
v6.12.0

**Comment by Kylart** [comment]
Is there no way you can upgrade to node 8 as it is the recommended version for most users?

**Comment by jm134** [comment]
so the recommedation for this script is node v8 right?

**Comment by Kylart** [comment]
It's true I should make it clear in the `README` and the `package.json`. I actually didn't expect people with lower versions to use this package 😄 

I can make it compatible with lower node version if you need though.

**Comment by jm134** [comment]
yeah you shoud add that thanks i will try now

**Comment by jm134** [comment]
all is working now but is there any way to get title only from myanimelist or livechart?

**Comment by Kylart** [comment]
You get livechart info only from `getSeason`

The rest is from MyAnimeList

**Comment by jm134** [comment]
so there is no way to get title only?

**Comment by Kylart** [comment]
Not from the package.

Though it is really easy to get an array with titles only. For example with `getSeason`
```javascript
const malScraper = require('mal-scraper')

malScraper.getSeason(2017, 'fall')
  .then((data) => {
    const titles = data.map((elem) => elem.title)

    console.log(titles)
  })
  .catch((err) => console.log(err.message))
```

**Comment by jm134** [comment]
data.map is not a function

**Comment by jm134** [comment]
new error
Request failed with status code 503

**Comment by Kylart** [comment]
Yea sorry, my previous script was a bit off
```javascript
const malScraper = require('mal-scraper')

malScraper.getSeason(2017, 'fall')
  .then((data) => {
    // Example for TV anime for this season
    const titles = data.TV.map((elem) => elem.title)

    console.log(titles)
  })
  .catch((err) => console.log(err.message))
```

As for the cloudflare issue, I can't really do anything, livechart seems offline. You should try again later

**Comment by jm134** [comment]
still same due cloudflare
btw how to use this https://www.npmjs.com/package/cfget
Request failed with status code 503

**Comment by Kylart** [comment]
Weird, I just tried and didn't get any cloudflare issue. Can you even access livechart.me from your browser? If no just wait a bit and try again when you'll be able to access this website.

As for your package, you can't use it with `mal-scraper`

**Comment by jm134** [comment]
from my browser it said wait 5 second due cloudflare
hmmm something wrong before this it ok

**Comment by jm134** [comment]
{ Error: Request failed with status code 503
    at createError (/home/pi/node_modules/mal-scraper/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/node_modules/mal-scraper/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/pi/node_modules/mal-scraper/node_modules/axios/lib/adapters/http.js:192:11)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.17.1' },
     method: 'get',
     url: 'https://www.livechart.me/fall-2017/tv',
     data: undefined },
  request: 
   ClientRequest {
     domain: null,
     _events: 
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 5,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'www.livechart.me',
        _readableState: [ReadableState],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 142,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 7,
        [Symbol(bytesRead)]: 5131,
        [Symbol(connect-options)]: [Object] },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'www.livechart.me',
        _readableState: [ReadableState],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 142,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 7,
        [Symbol(bytesRead)]: 5131,
        [Symbol(connect-options)]: [Object] },
     _header: 'GET /fall-2017/tv HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.17.1\r\nHost: www.livechart.me\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent: 
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path: '/fall-2017/tv',
     _ended: true,
     res: 
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 503,
        statusMessage: 'Service Temporarily Unavailable',
        client: [TLSSocket],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl: 'https://www.livechart.me/fall-2017/tv',
        read: [Function] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable: 
      Writable {
        _writableState: [WritableState],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _redirectCount: 0,
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'https://www.livechart.me/fall-2017/tv' },
     [Symbol(outHeadersKey)]: { accept: [Array], 'user-agent': [Array], host: [Array] } },
  response: 
   { status: 503,
     statusText: 'Service Temporarily Unavailable',
     headers: 
      { date: 'Thu, 16 Nov 2017 08:51:23 GMT',
        'content-type': 'text/html; charset=UTF-8',
        'transfer-encoding': 'chunked',
        connection: 'close',
        'set-cookie': [Array],
        'x-frame-options': 'SAMEORIGIN',
        refresh: '8;URL=/cdn-cgi/l/chk_jschl?pass=1510822287.898-tLppugKuuD',
        'cache-control': 'no-cache',
        'strict-transport-security': 'max-age=15552000; includeSubDomains; preload',
        'x-content-type-options': 'nosniff',
        server: 'cloudflare-nginx',
        'cf-ray': '3be9354a5c427086-SIN' },
     config: 
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'get',
        url: 'https://www.livechart.me/fall-2017/tv',
        data: undefined },
     request: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header: 'GET /fall-2017/tv HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.17.1\r\nHost: www.livechart.me\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/fall-2017/tv',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(outHeadersKey)]: [Object] },
     data: '<!DOCTYPE HTML>\n<html lang="en-US">\n<head>\n  <meta charset="UTF-8" />\n  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />\n  <meta name="robots" content="noindex, nofollow" />\n  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />\n  <title>Just a moment...</title>\n  <style type="text/css">\n    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}\n    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;}\n    h1 {font-size: 1.5em; color: #404040; text-align: center;}\n    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}\n    #spinner {margin: 0 auto 30px auto; display: block;}\n    .attribution {margin-top: 20px;}\n    @-webkit-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }\n    @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }\n    .bubbles { background-color: #404040; width:15px; height: 15px; margin:2px; border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; animation:bubbles 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:both; animation-fill-mode:both; display:inline-block; }\n  </style>\n\n    <script type="text/javascript">\n  //<![CDATA[\n  (function(){\n    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },\n    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};\n    b(function(){\n      var a = document.getElementById(\'cf-content\');a.style.display = \'block\';\n      setTimeout(function(){\n        var s,t,o,p,b,r,e,a,k,i,n,g,f, frOuzXP={"Q":!+[]+!![]+!![]+!![]+!![]};\n        t = document.createElement(\'div\');\n        t.innerHTML="<a href=\'/\'>x</a>";\n        t = t.firstChild.href;r = t.match(/https?:\\/\\//)[0];\n        t = t.substr(r.length); t = t.substr(0,t.length-1);\n        a = document.getElementById(\'jschl-answer\');\n        f = document.getElementById(\'challenge-form\');\n        ;frOuzXP.Q+=+((+!![]+[])+(!+[]+!![]+!![]+!![]+!![]));frOuzXP.Q-=+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]));frOuzXP.Q*=+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]));frOuzXP.Q*=+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]));frOuzXP.Q+=+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]));frOuzXP.Q+=+((+!![]+[])+(+[]));frOuzXP.Q+=+((!+[]+!![]+!![]+[])+(!+[]+!![]));frOuzXP.Q*=+((!+[]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]));a.value = parseInt(frOuzXP.Q, 10) + t.length; \'; 121\'\n        f.action += location.hash;\n        f.submit();\n      }, 4000);\n    }, false);\n  })();\n  //]]>\n</script>\n\n\n</head>\n<body>\n  <table width="100%" height="100%" cellpadding="20">\n    <tr>\n      <td align="center" valign="middle">\n          <div class="cf-browser-verification cf-im-under-attack">\n  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript>\n  <div id="cf-content" style="display:none">\n    \n    <div>\n      <div class="bubbles"></div>\n      <div class="bubbles"></div>\n      <div class="bubbles"></div>\n    </div>\n    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> livechart.me.</h1>\n    \n    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>\n    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>\n  </div>\n   \n  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">\n    <input type="hidden" name="jschl_vc" value="1d125c8ac5fdc23f31a337246b1ca6e9"/>\n    <input type="hidden" name="pass" value="1510822287.898-tLppugKuuD"/>\n    <input type="hidden" id="jschl-answer" name="jschl_answer"/>\n  </form>\n</div>\n\n          \n          <div class="attribution">\n            <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=iuam" target="_blank" style="font-size: 12px;">DDoS protection by Cloudflare</a>\n            <br>\n            Ray ID: 3be9354a5c427086\n          </div>\n      </td>\n     \n    </tr>\n  </table>\n</body>\n</html>\n' } }

**Comment by Kylart** [comment]
So it seems livechart added some security to their website, I'll be solving this as from tonight as I can't do it right now.
Hang tight

**Comment by jm134** [comment]
ok tqvm sir
