### ISSUE TITLE
breaking changes to xml2js

### ISSUE THREAD

**Issue by pendragons-code** [Kylart/MalScraper#109]
Yup, unfortunately this whole thing just got dumber.
https://github.com/Leonidas-from-XIV/node-xml2js/issues/667

**Comment by pendragons-code** [comment]
![image](https://user-images.githubusercontent.com/88629349/231840798-1a99a0c3-f415-4509-b7b2-009aa11e32df.png)

**Comment by Kylart** [comment]
Should be fixed by #113
