### ISSUE TITLE
2.12.1 release date ?

### ISSUE THREAD

**Issue by Aeden-B** [Kylart/MalScraper#110]
Without the type fix ab75d8700ee45e26dca17c861f346ed764320c47, the 2.12.0 release is unusable in a typescript project.

have you a release date for a 2.12.1 ?

**Comment by pendragons-code** [comment]
> Without the type fix [ab75d87](https://github.com/Kylart/MalScraper/commit/ab75d8700ee45e26dca17c861f346ed764320c47), the 2.12.0 release is unusable in a typescript project.
> 
> have you a release date for a 2.12.1 ?

I doubt that it would be quick, there are many issues that are already haunting this projects.

**Comment by Kylart** [comment]
You don't have to fix all the existing issues to deploy a release that has less issues.

I'll release 2.12.1 when I get back home tonight.

**Comment by pendragons-code** [comment]
True, but i thought you would make it a one shot fix release, that said, take care of yourself (you seem very busy)! :)

**Comment by Kylart** [comment]
2.12.1 is releasesd.
