### ISSUE TITLE
Not getting all episodes

### ISSUE THREAD

**Issue by Sawtaytoes** [Kylart/MalScraper#116]
I called `malScraper.getEpisodesList({ id, name })`, and it only gets me back 5 episodes for "Mushoku Tensei: Isekai Ittara Honki Dasu".

```
  [
    {
      epNumber: 1,
      aired: 'Jan 11, 2021',
      discussionLink: 'https://myanimelist.net/forum/?topicid=1885763',
      title: 'Jobless Reincarnation',
      japaneseTitle: 'Mushoku Tensei (無職転生)'
    },
    {
      epNumber: 2,
      aired: 'Jan 18, 2021',
      discussionLink: 'https://myanimelist.net/forum/?topicid=1885770',
      title: 'Master',
      japaneseTitle: 'Shishou (師匠)'
    },
    {
      epNumber: 3,
      aired: 'Jan 25, 2021',
      discussionLink: 'https://myanimelist.net/forum/?topicid=1891608',
      title: 'Friend',
      japaneseTitle: 'Tomodachi (友達)'
    },
    {
      epNumber: 4,
      aired: 'Feb 1, 2021',
      discussionLink: 'https://myanimelist.net/forum/?topicid=1893562',
      title: 'Emergency Family Meeting',
      japaneseTitle: 'Kinkyuu Kazokukaigi (緊急家族会議)'
    },
    {
      epNumber: 5,
      aired: 'Feb 8, 2021',
      discussionLink: 'https://myanimelist.net/forum/?topicid=1895593',
      title: 'A Young Lady and Violence',
      japaneseTitle: 'Ojou-sama to Bouryoku (お嬢様と暴力)'
    }
  ]
```

There are definitely 11 on the page:
![image](https://github.com/Kylart/MalScraper/assets/3948069/d8801b3f-c657-4c21-8b51-c93635882d1e)

**Comment by Sawtaytoes** [comment]
Looking at `episodes.js`, I think the issue is that `'tr.episode-list-data'` no longer exists after another recursive loop. Not sure what `offset + 100` means, but it might be set too high.

The HTML returns the episodes, but after you do another `searchPage`, I'm assuming `'tr.episode-list-data'` no longer in the HTML.

If we only had a search for `"td.episode-number"`, I'm assuming it'd work just fine.

But all of this could be completely wrong.

I did test with incrementing the offset by 1 and 2. Both did return me more episodes: 10 and 9 respectively. Something funky's going on here.

**Comment by Sawtaytoes** [comment]
I see it now. It looks like this bug was fixed:

![image](https://github.com/Kylart/MalScraper/assets/3948069/b50f8c86-c02e-4760-b8ef-11d686391302)

**Comment by Kylart** [comment]
> I see it now. It looks like this bug was fixed:

I guess we can close this then? Feel free to reopen if necessary
