### ISSUE TITLE
problem getting title

### ISSUE THREAD

**Issue by jm134** [Kylart/MalScraper#12]
how to getting title for new season without leftover (TV Continuing). please take a look here
spring 2018
https://pastebin.com/fXbsrzQZ
summer 2018
i have marked some leftover
https://pastebin.com/tkKAy5wQ

what i'm trying to achieve here were getting title without leftover (TV Continuing)
could we scaping season from this link?
https://www.livechart.me/summer-2018/tv?leftovers=false
summer for season 2018 for year

**Comment by Kylart** [comment]
What is retrieved are the name given by MAL, e.g. [this page](https://myanimelist.net/anime/season). No post-processing is being applied afterwards.

The point of this library is to get information from [myanimelist.net](https://myanimelist.net) so no, it's not possible to get the seasonal information from livechart. Some other library should exist to do that though.

**Comment by jm134** [comment]
Thanks for answering my question. btw this scraper is so helpful keep it up :)
