### ISSUE TITLE
takes few seconds to fetch

### ISSUE THREAD

**Issue by dragneel30** [Kylart/MalScraper#18]
Im trying to the api and takes around 10 seconds to fetch something. (ex: 2019 summer)
is there some kind of pre requisite for the api?

**Comment by Kylart** [comment]
Hello,

I'll need more insights, the only reason I can imagine for such behaviour is slow connection. The time to fetch something like the season is approximately the same as the time to see [this page](https://myanimelist.net/anime/season).

So, two possibilities here:
1. You have a slow connection or drops/loss.
2. MyAnimeList servers are slow to answer.

I'm sorry I cannot do much to significantly increase the speed it takes to fetch the page 😞
