### ISSUE TITLE
[Feature Request]: Add Japanese fields

### ISSUE THREAD

**Issue by kanjieater** [Kylart/MalScraper#24]
It doesn't look like the Japanese name for the field is currently supported for Japanese names, as seen here: https://myanimelist.net/manga/23390/Shingeki_no_Kyojin
`進撃の巨人`

Is it possible to add this data? Is it possible to search by Japanese title?

**Comment by Kylart** [comment]
I am not sure what you are referring to.

If you do things like
```javascript

getInfoFromURL('https://myanimelist.net/manga/23390/Shingeki_no_Kyojin')
  .then(console.log)
  .catch(console.log)
  
getInfoFromName('進撃の巨人')
  .then(console.log)
  .catch(console.log)
```

You'll have all the information you asked for, especially the japanese name under the property `japaneseTitle`
