### ISSUE TITLE
Can't check credentials

### ISSUE THREAD

**Issue by LightYagami200** [Kylart/MalScraper#31]
**What I'm trying to do:**
I'm trying to check credentials of user trying to login

**Error**
`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">                                                                      <html><head>                                                                                                            <title>404 Not Found</title>                                                                                            </head><body>                                                                                                           <h1>Not Found</h1>                                                                                                      <p>The requested URL /api/account/verify_credentials.xml was not found on this server.</p>                              <p>Additionally, a 404 Not Found                                                                                        error was encountered while trying to use an ErrorDocument to handle the request.</p>                                   </body></html>  `

**Source Code**
`const api = new malScraper.officialApi({
        username: username,
        password: password,
      });

      try {
        const res = await api.checkCredentials();
        console.log(res);
      } catch (e) {
        console.log(e);
      }`

**Comment by Kylart** [comment]
Hey,

This feature uses the official MAL API which is down for years now. That's why it won't work.

However, depending on your usecase. You can implement the authentication system described [here](https://github.com/jikan-me/jikan-auth/blob/master/SPECIFICATION.md).
