### ISSUE TITLE
Search.search() misplaced value in data model

### ISSUE THREAD

**Issue by raf555** [Kylart/MalScraper#32]
Hello there, apparently there is some misplaced value in search.search() data model, here is the screenshot.

![image](https://user-images.githubusercontent.com/8206338/83328050-97044180-a2aa-11ea-979e-daa21c794cfc.png)

**Comment by Kylart** [comment]
Hey,

Could you give me the code that resulted to this? It'd help a lot troubleshooting / fixing this!

Thanks

**Comment by raf555** [comment]
Apparently, search.search() data model only works on anime-type search, it doesn't work on manga-type search, this is my code.
![image](https://user-images.githubusercontent.com/8206338/83593730-ac69bc00-a587-11ea-9080-6a10fbd67d2f.png)

**Comment by Kylart** [comment]
`v2.7.0` just got released with that fixed.

There now are `vols` and `nbChapters` as well!
