### ISSUE TITLE
Can't use MalScraper because anything results 403 forbidden

### ISSUE THREAD

**Issue by raf555** [Kylart/MalScraper#33]
Hello there, recently i am having this problem. MalScraper won't give the result, instead it returns '403 forbidden'. 

I am using glitch.com server, i tried to my different project but the result is still the same, I don't know it's just server-side error or same problem to anyone, i hope you can provide help, thanks.

Here is the log
https://drive.google.com/file/d/1LhsB--hf-DKGyBjKZg06kbwSF3NurkLm/view?usp=drivesdk

**Comment by EduardoMateus** [comment]
I believe that everyone has this problem, MAL blocked several

**Comment by raf555** [comment]
> I believe that everyone has this problem, MAL blocked several

Soo it can't be helped until MAL lift the ban hammer

**Comment by HellpMe** [comment]
I have the same error, someone there managed to find out what it is?

**Comment by HellpMe** [comment]
I have the same error, did anyone there find out what it is?

**Comment by HellpMe** [comment]
I have the same error, did anyone there find out what it is?

**Comment by raf555** [comment]
> I have the same error, did anyone there find out what it is?

it probably comes from MAL itself, as @EduardoMateus said

**Comment by EduardoMateus** [comment]
I have an application that needs MAL, but it blocked

**Comment by EduardoMateus** [comment]
Nop

**Comment by raf555** [comment]
MalScraper suddenly works in my project, are you guys too?

**Comment by Kylart** [comment]
So this was definitely a problem on MAL. Apparently they were dealing with a lot of requests at the time.
