### ISSUE TITLE
Timed out while running tests

### ISSUE THREAD

**Issue by JustalK** [Kylart/MalScraper#36]
Hello,

I have been interested by your scrapper for MAL but by running your test, I am facing this problem :
`npm test`

```
Timed out while running tests
```

After multiple try, I manage to see that it always appends on the same part of the code. By example, for the test checking that Naruto has 500 episode, you have a 5 recursive calls. You get all the pages one after the other. Same goes for Drifters. But Ava has a timeout error trigger if the connection is a bit too long. 

![aaaa](https://user-images.githubusercontent.com/5208910/90543019-97c8b780-e1b7-11ea-84d0-4b6dc18b1cfd.png)

**Comment by JustalK** [comment]
it seems to work if I add the timeout to 1min
![Screenshot from 2020-08-19 01-12-20](https://user-images.githubusercontent.com/5208910/90544120-428da580-e1b9-11ea-9102-bbdb6cf1da76.png)

**Comment by Kylart** [comment]
So this definitely happens when MAL has problems answering requests and does not come from the library. Hence I'm closing this.
