### ISSUE TITLE
Anime Search data model resulted wrong information

### ISSUE THREAD

**Issue by raf555** [Kylart/MalScraper#37]
![image](https://user-images.githubusercontent.com/8206338/91244680-240a4a00-e777-11ea-9945-d0df963cc60f.png)

As you can see in the image, title, synopsis, and picture are not defined and wrong, this error probably comes from MAL, who may change something on the page. Please fix, thank you.

**Comment by raf555** [comment]
I checked a bit your code, you use "span" tag to retrieve data, apparently MAL changes this to "div". I suppose that is the problem

**Comment by raf555** [comment]
I checked your code a bit, you used "span" tag to retrieve data, apparently MAL changes this to "div". I suppose that is the problem

**Comment by nzkdevsaider** [comment]
> I checked your code a bit, you used "span" tag to retrieve data, apparently MAL changes this to "div". I suppose that is the problem

Yes, this is caused by a change in the MAL page.

**Comment by SammyWhamy** [comment]
Same issue here, would be great if it got fixed

**Comment by Kylart** [comment]
This is now fixed in version 2.7.2.
