### ISSUE TITLE
title and synopsis undefined

### ISSUE THREAD

**Issue by gco360** [Kylart/MalScraper#41]
well i am using mal-scraper and it doesn't show the tittle of the anime also it doesn't show the synopsis
![Screenshot_2](https://user-images.githubusercontent.com/31587917/92268383-e5575b00-eeff-11ea-8642-b8fc67d74352.png)

**Comment by Kylart** [comment]
Duplicate #37 #38 #39 ..

TLDR: Update to 2.7.2
