### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 7thghoul** [Kylart/MalScraper#53]
TypeError: Cannot read property 'url' of undefined
    at C:\Users\7thghoul\node_modules\mal-scraper\src\info.js:222:33
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Kylart** [comment]
I'd need more information on what code you ran to have this error.

**Comment by Sazzo** [comment]
The error is happening to me when I run this code:
```js
const malAnime = await mal.getInfoFromName(name)
```
I hope this helps, it happens sometimes and is very annoying.

**Comment by 7thghoul** [comment]
const name = "gakkou gurashi"
Try it, it'll return an url error.

**Comment by Gabb-c** [comment]
Yup . . .
![image](https://user-images.githubusercontent.com/65926741/95680291-ed658300-0bae-11eb-9645-4b85545339f0.png)
![image](https://user-images.githubusercontent.com/65926741/95680300-066e3400-0baf-11eb-85b6-749e2e912bcd.png)

**Comment by Kylart** [comment]
How about a specific name that triggers it? It'd help a lot.

**Comment by Kylart** [comment]
This is fixed and deployed in v2.11.2.

Thanks for the bug report!
