### ISSUE TITLE
getSeason returned an empty object

### ISSUE THREAD

**Issue by Gabb-c** [Kylart/MalScraper#54]
When I tryed getSeason('2020', 'summer') it returns an empty object in the array:

![image](https://user-images.githubusercontent.com/65926741/95002693-47fa5000-05ad-11eb-9857-d0942501428b.png)

**Comment by Gabb-c** [comment]
But the scraper is very nice!

**Comment by Kylart** [comment]
A fix for this is deployed in v2.11.1. Thanks for reporting this and the kind words 😄

**Comment by Gabb-c** [comment]
Thanks for fixing it. I'm using your scraper in my discord.js bot. Take a look:

https://github.com/Gabb-c/CanuhBot
