### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Sazzo** [Kylart/MalScraper#60]
Getting this error when I try to get information about an anime by name using the function:
``getInfoFromName()``

Error Stack:
```
Cannot read property 'forEach' of undefined
   at node_modules/mal-scraper/src/info.js:193:23
   at runMicrotasks (<anonymous>)
   at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I hope it will be fixed soon!

**Comment by Sazzo** [comment]
I think it's probably because of the problems with MyAnimeList today (like blank screen), I will hope to return.

**Comment by Gabb-c** [comment]
> I think it's probably because of the problems with MyAnimeList today (like blank screen), I will hope to return.

Checked your discord bot. So cool. Add me on discord: Gabb-c#8936

**Comment by Sazzo** [comment]
> > I think it's probably because of the problems with MyAnimeList today (like blank screen), I will hope to return.
> 
> Checked your discord bot. So cool. Add me on discord: Gabb-c#8936

Haha, thanks! I sent a friend request.
