### ISSUE TITLE
high vulnerability 

### ISSUE THREAD

**Issue by aikozijlemans** [Kylart/MalScraper#61]
High            Server-Side Request Forgery                                   
                                                                                
  Package         axios                                                         
                                                                                
  Patched in      >=0.21.1                                                      
                                                                                
  Dependency of   mal-scraper                                                   
                                                                                
  Path            mal-scraper > axios                                           
                                                                                
  More info       https://npmjs.com/advisories/1594

**Comment by Yaroster** [comment]
https://github.com/axios/axios/commit/c7329fefc890050edd51e40e469a154d0117fc55

Here's how to preven SSRF in axios.

**Comment by Kylart** [comment]
This is updated and deployed in v2.11.3
