### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Zargdreon** [Kylart/MalScraper#62]
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "mal-scraper" under a package
npm ERR! also called "mal-scraper". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Berthens\AppData\Roaming\npm-cache\_logs\2021-02-24T20_04_35_359Z-debug.log

**Comment by Kylart** [comment]
I'd need more context to help with that but it does not seem to come from the package itself.

It seems you are trying to install this package within a project called `mal-scraper` and npm does not allow you to do that.

**Comment by Gabb-c** [comment]
It might be your Node version. I recommend the 14.15.5. The latest version (at the moment, 15.10.0) it's getting me lots of bugs.
