### ISSUE TITLE
Support 

### ISSUE THREAD

**Issue by Xx-Mohit-xX** [Kylart/MalScraper#72]
Is there any way to add Nsfw / safe word filter to this
```js
malScraper.getInfoFromName()
```

**Comment by Yaroster** [comment]
Just by pure curiousity what kind of NSFW data could you ever get by using getInfoFromName() ?

Anyways if you don't get an answer you could use [this](https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/blob/master/en) when parsing your data to filter it.

**Comment by Xx-Mohit-xX** [comment]
> Just by pure curiousity what kind of NSFW data could you ever get by using getInfoFromName() ?
> 
> Anyways if you don't get an answer you could use [this](https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/blob/master/en) when parsing your data to filter it.

Like hentai,  i want it to so i dont show any hentai or other nsfw stuff. My bot is sfw bot and i do lile to use this function. If you gets add any nsfw filter or non hentaiode or something it will be good

**Comment by Rapougnac** [comment]
@Xx-Mohit-xX You can't just check if the rating is `Rx - Hentai` and if then, stop the user?

**Comment by Xx-Mohit-xX** [comment]
> @Xx-Mohit-xX You can't just check if the rating is `Rx - Hentai` and if then, stop the user? 

Oh yeah, got it ty

**Comment by Xx-Mohit-xX** [comment]
> @Xx-Mohit-xX You can't just check if the rating is `Rx - Hentai` and if then, stop the user? 

I can or I can

**Comment by Rapougnac** [comment]
> I can or I can
What do you mean?

**Comment by Xx-Mohit-xX** [comment]
> > I can or I can
> 
> What do you mean?

Nothing I got it ty
