### ISSUE TITLE
getRecommendationsList parameter object does not need name

### ISSUE THREAD

**Issue by platers** [Kylart/MalScraper#75]
`malScraper.getRecommendationsList({
  name: 'Sakura Trick',
  id: 20047
})` has the same result as 
`malScraper.getRecommendationsList({
  name: 'anything',
  id: 20047
})`
Looks like MAL doesn't care about the name. Ex https://myanimelist.net/anime/73/anything/userrecs works.

getRecommendationsList should be callable with just an id, no need to provide a name.

**Comment by Kylart** [comment]
Thanks for the callout!
