### ISSUE TITLE
Next Release ?

### ISSUE THREAD

**Issue by Aeden-B** [Kylart/MalScraper#99]
Hello,

I would like to know when the next release is planned?

Thanks.

**Comment by LegendaryEmoji** [comment]
I am working on the next major update, v3.0.0 (check #90 for more info).

I expect this to take 1-2 weeks. Suggestions and new features are welcomed.

**Comment by Kylart** [comment]
Sorry I was a bit busy, I'll try to release the latest changes later today

**Comment by Kylart** [comment]
I just released v2.12.0
